server:
  port: 8888
  servlet:
    context-path: /HelloWorld/
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_springboot?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  config: log4j2-spring.xml
  level:
    cn.jay.repository: trace